[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = ""
authors = ["Emil Murzin <emil.morua@gmail.com>"]
readme = "README.md"
packages = [{include = "find_diff"}]

[tool.poetry.dependencies]
python = "^3.10.6"

[tool.poetry.scripts]
gendiff = "find_diff.scripts.entrance_point:main"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
